cloudrive:
  storage:
    directory: c:\\temp\\storage
    create_if_not_exists: true
    tempfilder: 8da8d664-4882-4391-98bb-70aa921cdc30
    previewfolder: previews
  web.server-url: http://localhost:8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/webcloudrive
    username: cloudrive
    password: cloudrive
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true


  # Mailer
  mail:
    host: smtp.yandex.ru
    port: 587
    # username: username # << edit here
    # password: password # << and here

    # Other properties
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG


oauth2:
  facebook:
    client:
      clientId: # ***
      clientSecret: # ***
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
  google:
    client:
      clientId: # ***
      clientSecret: # ***
      clientAuthenticationScheme: form
      scope: openid,email,profile
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true